services:
  - docker
sudo: true
script:
  - docker run -v $(pwd):/travis ubuntu:latest bash -c 'cd /travis; ./build-mcpe.sh; ./build-repo.sh'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: repo
  on:
    branch: master
