version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - run:
          name: Update APT
          command: apt update
      - run:
          name: Install Sudo
          command: apt install -y sudo
      - checkout
      - run:
          name: Build MCPELauncher
          command: ./build-mcpe.sh
      - run:
          name: Build Repo
          command: ./build-repo.sh
      - run:
          name: Deploy To Github Pages
          command: ./deploy.sh
