version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Get Version
          command: lsb_release -a
      - checkout
      - run:
          name: Build MCPELauncher
          command: ./build-mcpe.sh
      - run:
          name: Build Repo
          command: ./build-repo.sh
